# Auto-promotes claude/** branches to main after successful push
name: Auto-promote Claude branch to main
on:
  push:
    branches:
      - "claude/**"
permissions:
  contents: write
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Merge branch into main
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff "origin/$BRANCH" -m "auto: promote $BRANCH into main" || {
            echo "Merge conflict detected, resolving..."
            # For workflow files that were deleted in main, keep the version from the branch
            git checkout --theirs .github/workflows/ 2>/dev/null || true
            git add .github/workflows/ 2>/dev/null || true
            # Check if there are still conflicts
            if git diff --name-only --diff-filter=U | grep -q .; then
              echo "Unresolved conflicts remain:"
              git diff --name-only --diff-filter=U
              exit 1
            fi
            git commit --no-edit
          }
          git push origin main
